### ISSUE TITLE
폴더 구조 제안

### ISSUE THREAD

**Issue by los56** [charBS0701/linkive-web-front-react#1]
리액트 프로젝트 구조를 다른 개발자분들은 어떻게 구성하시나 해서 검색해보니까 조금씩은 다른데 공통적으로 비슷한건

components/ : 여러 페이지에서 공용으로 사용하는 컴포넌트
contents/ : 이미지 등과 같은 리소스들
pages/ : 라우팅 되는 각 페이지와 해당 페이지 구성을 위한 컴포넌트

로 많이 구성하셔서 비슷하게 제 브렌치에 정리해봤는데 이 방식이 괜찮을지 의견 부탁드립니다.

**Comment by charBS0701** [comment]
좋아요
